'use client';
import { useCallback, useEffect, useState } from 'react';
import Sidebar from '@/components/Sidebar';
import DashboardHeader from '@/components/DashboardHeader';
import {treasuryRequest,record,rows,display,minor,Row} from '@/lib/api/treasury';
import {actions,Action} from './actions';

const views:Record<string,string>={'Capital receipts':'treasury/operations/lists/capital',Observations:'treasury/operations/lists/observations',Orders:'treasury/operations/lists/orders',Replenishments:'treasury/operations/lists/replenishments',Pools:'treasury/operations/lists/pools',Rules:'treasury/operations/lists/rules',Cohorts:'treasury/operations/lists/cohorts','Cohort wallets':'treasury/operations/lists/cohort-wallets',Alerts:'treasury/operations/lists/alerts','Audit records':'treasury/operations/lists/audit',Stages:'treasury/operations/lists/stages',Locations:'treasury/locations',Positions:'treasury/bridge/positions',Movements:'treasury/bridge/movements',Payouts:'treasury/payouts',Accounts:'treasury/accounts',Journals:'treasury/journals'};
const button='rounded-xl bg-[#004D43] text-white px-4 py-2 disabled:opacity-40 disabled:cursor-not-allowed';
export default function TreasuryPage(){
 const [permissions,setPermissions]=useState<Record<string,boolean>>({}),[overview,setOverview]=useState<Row>({}),[data,setData]=useState<Row[]>([]),[view,setView]=useState('Orders'),[page,setPage]=useState(1),[last,setLast]=useState(1),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [action,setAction]=useState<Action>(actions[0]),[form,setForm]=useState<Record<string,string>>({}),[review,setReview]=useState<{path:string;body:Row}|null>(null),[result,setResult]=useState<unknown>(null);
 const reload=useCallback(async()=>{setLoading(true);try{const [p,o,list]=await Promise.all([treasuryRequest('treasury/operations/capabilities'),treasuryRequest('treasury/operations/overview'),treasuryRequest(`${views[view]}?page=${page}`)]);setPermissions(p as Record<string,boolean>);setOverview(record(o));const l=record(list);setData(rows(l.data??list));setLast(Number(l.last_page??1));}catch(e){setError(String(e));}finally{setLoading(false);}},[view,page]);
 useEffect(()=>{void reload();},[reload]);
 function prepare(e:React.FormEvent){e.preventDefault();setError('');try{let path=action.path;const body:Row={};for(const f of action.fields){let value:unknown=form[f.key]??'';if(f.type==='boolean')value=value==='true';else if(f.type==='number'){if(value===''&&f.optional){value=null;}else{const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw Error(`${f.label}: enter a positive ID`);value=n;}}else if(f.type==='ids'){value=String(value).split(',').map(s=>Number(s.trim()));if(!(value as number[]).length||(value as number[]).some(n=>!Number.isSafeInteger(n)||n<1))throw Error('Enter valid wallet IDs.');}if(path.includes(`{${f.key}}`))path=path.replace(`{${f.key}}`,encodeURIComponent(String(value)));else body[f.key]=value;}setReview({path,body});}catch(e){setError(String(e));}}
 async function submit(){if(!review||busy)return;setBusy(true);setError('');try{const r=await treasuryRequest(review.path,action.method??'POST',review.body);setResult(r);setNotice('Request acknowledged. Review the returned state and refreshed records; acknowledgement alone does not mean settlement completed.');setReview(null);await reload();}catch(e){setError(`${String(e)} If the connection failed, refresh the relevant record before retrying.`);setReview(null);}finally{setBusy(false);}}
 return <div className="min-h-screen bg-[#F6F9F8] flex"><div className="hidden md:flex shrink-0"><Sidebar/></div><main className="min-w-0 flex-1 p-4 lg:p-8"><details className="md:hidden mb-4"><summary>Navigation</summary><Sidebar/></details><DashboardHeader title="Treasury"/><div className="max-w-7xl mx-auto space-y-6"><header className="flex justify-between items-center"><div><h1 className="text-3xl font-semibold text-[#004D43]">Treasury & settlement</h1><p className="text-gray-600">Customer backing, company liquidity and recoverable orders</p></div><button className={button} disabled={busy||loading} onClick={()=>{setError('');void reload();}}>Refresh</button></header>
 {error&&<p role="alert" className="bg-red-50 text-red-800 p-4 rounded-xl">{error}</p>}{notice&&<p role="status" className="bg-green-50 p-4 rounded-xl">{notice}</p>}{loading&&<p role="status">Loading verified treasury records…</p>}
 {permissions['treasury.view']&&<>
 <section className="grid md:grid-cols-3 gap-4">{rows(overview.pools).map(p=><article key={String(p.currency)} className="bg-white border rounded-2xl p-5"><h2 className="font-bold text-xl">{display(p.currency)} pool</h2><p className="text-sm text-gray-500">Free company liquidity</p><p className="text-2xl my-2">{minor(p.company_available_minor)} {display(p.currency)}</p><p className="text-sm">Observed assets: {minor(p.observed_native_minor,p.currency==='USD'?6:2)} {p.currency==='USD'?'settlement asset':display(p.currency)}</p><p className="text-sm">Accounted + unmigrated: {minor(p.accounted_and_unmigrated_native_minor,p.currency==='USD'?6:2)}</p><p className="text-xs mt-3">Observed: {display(p.observed_at)}</p></article>)}</section>
 <section className="bg-white rounded-2xl border p-5"><h2 className="text-xl font-semibold">Reconciliation: {display(overview.state)}</h2><p className="text-sm">Treasury alerts: {record(overview.alert_settings).treasury?'on':'off'} · Replenishment alerts: {record(overview.alert_settings).replenishment?'on':'off'} · Automatic replenishment: {overview.automatic_replenishment?'on':'off'}</p><p className="text-xs text-gray-500">These switches are managed through deployment ENV settings.</p>{rows(overview.issues).map((issue,i)=><p key={i} className="mt-2 text-amber-800">{display(issue.code).replaceAll('_',' ')} {issue.currency?display(issue.currency):''} {issue.wallet_id?`Wallet ${issue.wallet_id}`:''} {issue.count?`(${issue.count})`:''}</p>)}</section>
 <section className="bg-white rounded-2xl border p-5 space-y-4"><div className="flex flex-wrap gap-2">{Object.keys(views).map(v=><button key={v} disabled={busy||loading} onClick={()=>{setView(v);setPage(1);}} className={`px-3 py-2 rounded-lg ${view===v?'bg-[#004D43] text-white':'bg-gray-100'}`}>{v}</button>)}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{Array.from(new Set(data.flatMap(r=>Object.keys(r)))).filter(k=>!['pricing','details','snapshot','metadata'].includes(k)).map(k=><th key={k} className="text-left p-3 whitespace-nowrap">{k.replaceAll('_',' ')}</th>)}<th>Inspect</th></tr></thead><tbody>{data.map((r,i)=><tr key={String(r.id??i)} className="border-t">{Array.from(new Set(data.flatMap(r=>Object.keys(r)))).filter(k=>!['pricing','details','snapshot','metadata'].includes(k)).map(k=><td className="p-3 max-w-xs break-words" key={k}>{display(r[k])}</td>)}<td><button className="underline" onClick={()=>{setResult(r);if(r.id)setForm({...form,id:String(r.id)});}}>Details / use ID</button></td></tr>)}</tbody></table></div>{data.length===0&&!loading&&<p>No records.</p>}<div className="flex justify-between"><button disabled={page<=1||loading||busy} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {last}. Amount columns ending in minor use minor units.</span><button disabled={page>=last||loading||busy} onClick={()=>setPage(page+1)}>Next</button></div></section>
 <section className="bg-white rounded-2xl border p-5"><h2 className="text-xl font-semibold mb-4">Treasury actions</h2><select className="border rounded-lg p-3 w-full" disabled={busy} value={action.name} onChange={e=>{setAction(actions.find(a=>a.name===e.target.value)!);setForm({});setReview(null);}}>{actions.map(a=><option key={a.name} value={a.name} disabled={!permissions[a.permission]}>{a.name}{permissions[a.permission]?'':' (permission required)'}</option>)}</select><p className="my-3 text-gray-600">{action.note}</p><form onSubmit={prepare} className="grid md:grid-cols-2 gap-4">{action.fields.map(f=><label className="flex flex-col gap-1" key={f.key}>{f.label}{f.optional?' (optional)':''}{f.options||f.type==='boolean'?<select disabled={busy} required={!f.optional} className="border rounded-lg p-3" value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">Select</option>{(f.options??['false','true']).map(v=><option key={v}>{v}</option>)}</select>:f.type==='textarea'?<textarea required disabled={busy} className="border rounded-lg p-3" value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input required={!f.optional} disabled={busy} className="border rounded-lg p-3" value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}<button className={button} disabled={busy||!permissions[action.permission]}>Review action</button></form></section>
 {result!=null&&<details open className="bg-white p-5 rounded-xl border"><summary>Record / last response</summary><pre className="overflow-auto max-h-96 text-xs p-3">{JSON.stringify(result,null,2)}</pre></details>}
 </>}
 {review&&<div role="dialog" aria-modal="true" aria-label="Confirm treasury action" className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-6 max-w-xl w-full max-h-[90vh] overflow-auto"><h2 className="text-xl font-bold">{action.name}</h2><p className="my-3">{action.note??'Confirm the selected identifiers and review evidence before applying.'}</p><p className="break-all text-sm">Target: {review.path}</p><pre className="overflow-auto bg-gray-50 p-3 my-4">{JSON.stringify(review.body,null,2)}</pre><div className="flex gap-3"><button disabled={busy} onClick={()=>setReview(null)}>Back</button><button disabled={busy} className={button} onClick={()=>void submit()}>{busy?'Processing…':'Confirm action'}</button></div></div></div>}
 </div></main></div>;
}
