'use client';
import {useCallback,useEffect,useState} from 'react';
import {treasuryRequest,record,rows,display,Row} from '@/lib/api/treasury';
const providers=['open_exchange_rates','currencyapi','exchange_rate_api','abokifx'];
const fields:Record<string,{key:string;label:string;options?:string[]}[]>={
 pair:[{key:'from_currency',label:'Source wallet',options:['NGN','USD','YUAN']},{key:'to_currency',label:'Destination wallet',options:['NGN','USD','YUAN']},{key:'rate_source',label:'Rate source',options:['provider','manual']},{key:'provider',label:'Pricing provider / label',options:providers},{key:'manual_rate',label:'Manual rate (destination units per source unit)'},{key:'markup_percent',label:'Markup percentage'},{key:'markup_operation',label:'Apply markup',options:['add','subtract']}],
 provider:[{key:'key',label:'Provider',options:providers},{key:'max_age_seconds',label:'Maximum rate age (seconds)'},{key:'api_key',label:'API key (stored encrypted)'},{key:'parameters_json',label:'Extra parameters JSON (optional)'}],
 currency:[{key:'currency',label:'Wallet currency',options:['NGN','USD','YUAN']},{key:'provider_code',label:'Provider currency code (NGN, USD, CNY or CNH)'},{key:'scale',label:'Decimal places'}],
};
export default function FxPricingPanel({editable}:{editable:boolean}){
 const [snapshot,setSnapshot]=useState<Row>({}),[comparison,setComparison]=useState<Row[]>([]),[kind,setKind]=useState('pair'),[form,setForm]=useState<Record<string,string>>({enabled:'false'}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<Row|null>(null),[loaded,setLoaded]=useState(false),[audit,setAudit]=useState<Row[]>([]),[auditPage,setAuditPage]=useState(1),[auditLast,setAuditLast]=useState(1);
 const load=useCallback(async()=>{setBusy(true);try{const [s,c]=await Promise.all([treasuryRequest('fx/pricing'),treasuryRequest('fx/pricing/comparison')]);setSnapshot(record(s));setComparison(rows(c));setLoaded(true);}catch(e){setError(String(e));}finally{setBusy(false);}},[]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{treasuryRequest(`fx/pricing/audit?page=${auditPage}`).then(v=>{const a=record(v);setAudit(rows(a.data));setAuditLast(Number(a.last_page??1));}).catch(e=>setError(String(e)));},[auditPage,snapshot]);
 async function refresh(provider:string){setBusy(true);setError('');try{await treasuryRequest(`fx/pricing/providers/${provider}/refresh`,'POST',{});await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function save(){if(!review)return;setBusy(true);setError('');try{await treasuryRequest(`fx/pricing/settings/${kind}`,'PUT',review);setReview(null);await load();}catch(e){setError(`${String(e)} Refresh settings before retrying; another admin may have changed the revision.`);setReview(null);}finally{setBusy(false);}}
 return <section className="bg-white rounded-2xl border p-5 space-y-4"><h2 className="font-semibold text-xl">FX pricing and comparison</h2><p>Set a provider rate or choose Manual rate. Manual rates remain usable when a provider is disabled or pending. Provider keys are encrypted and never displayed. Manual rates ignore percentage markup.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<button onClick={()=>void load()} disabled={busy} className="underline">Refresh settings</button><div className="grid md:grid-cols-2 gap-3">{comparison.map(p=><article className="border rounded-xl p-4" key={String(p.provider)}><h3 className="font-semibold">{display(p.provider).replaceAll('_',' ')}</h3><p>{p.enabled?'Enabled':'Disabled'} · {p.stale?'Stale or missing':'Fresh'}{p.comparison_only?' · Comparison only':''}</p><p className="text-sm">As of {display(p.as_of)}</p><details><summary>Provider rates</summary><pre className="max-h-60 overflow-auto text-xs">{JSON.stringify(p.rates,null,2)}</pre></details><button className="underline mt-2 disabled:opacity-40" disabled={busy||!editable} onClick={()=>void refresh(String(p.provider))}>Fetch latest rates</button></article>)}</div>
 <div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['Direction','Source','Rate','Markup','Enabled','Edit'].map(c=><th className="p-2 text-left" key={c}>{c}</th>)}</tr></thead><tbody>{rows(snapshot.pairs).map((p,i)=><tr className="border-t" key={i}><td>{display(p.from_currency)} → {display(p.to_currency)}</td><td>{display(p.rate_source||'provider')}</td><td>{display(p.manual_rate||p.provider)}</td><td>{display(p.markup_percent)}%</td><td>{p.enabled?'Yes':'No'}</td><td><button disabled={!editable||busy} className="underline" onClick={()=>{setKind('pair');setForm(Object.fromEntries(Object.entries(p).map(([k,v])=>[k,String(v)])));}}>Edit</button></td></tr>)}</tbody></table></div>
 <form className="grid md:grid-cols-2 gap-4" onSubmit={e=>{e.preventDefault();const body:Row={...form,revision:Number(snapshot.revision),enabled:form.enabled==='true'};if(kind==='provider')body.max_age_seconds=Number(form.max_age_seconds);if(kind==='currency')body.scale=Number(form.scale);setReview(body);}}><label className="flex flex-col">Settings type<select disabled={busy||!editable} className="border p-2 rounded" value={kind} onChange={e=>{setKind(e.target.value);setForm({enabled:'false'});}}>{Object.keys(fields).map(k=><option key={k}>{k}</option>)}</select></label>{fields[kind].map(f=><label className="flex flex-col" key={f.key}>{f.label}{f.options?<select required disabled={busy||!editable} className="border p-2 rounded" value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">Select</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:<input required disabled={busy||!editable} className="border p-2 rounded" value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}<label className="flex flex-col">Enabled<select value={form.enabled} disabled={busy||!editable} className="border p-2 rounded" onChange={e=>setForm({...form,enabled:e.target.value})}><option value="false">No</option><option value="true">Yes</option></select></label><label className="flex flex-col">Reason<textarea required disabled={busy||!editable} className="border p-2 rounded" value={form.reason??''} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button disabled={busy||!editable||!loaded} className="bg-[#004D43] text-white rounded-xl p-3 disabled:opacity-40">Review pricing change</button></form>
 <details><summary>Pricing audit history</summary>{audit.map((a,i)=><div className="border-b py-2 text-sm" key={i}><strong>{display(a.action)}</strong> · Admin {display(a.actor_id)} · {display(a.created_at)}<p>{display(a.reason)}</p><details><summary>Change details</summary><pre className="overflow-auto">{display(a.details)}</pre></details></div>)}<button disabled={auditPage<=1} onClick={()=>setAuditPage(auditPage-1)}>Previous</button><span className="mx-4">{auditPage} / {auditLast}</span><button disabled={auditPage>=auditLast} onClick={()=>setAuditPage(auditPage+1)}>Next</button></details>
 {review&&<div role="dialog" aria-modal="true" aria-label="Review FX change" className="fixed inset-0 bg-black/50 z-50 grid place-items-center p-4"><div className="bg-white rounded-2xl p-6 max-w-xl w-full"><h3 className="font-bold text-xl">Confirm pricing change</h3><p>Changing settings invalidates unaccepted quotes. Accepted orders retain their agreed amounts.</p><pre className="my-4 overflow-auto">{JSON.stringify(review,null,2)}</pre><button disabled={busy} onClick={()=>setReview(null)} className="mr-4">Back</button><button disabled={busy} onClick={()=>void save()} className="bg-[#004D43] text-white p-3 rounded-xl">{busy?'Saving…':'Confirm'}</button></div></div>}
 </section>;
}
